version: '3'

services:

  php-fpm:
    build:
      context: ./
      dockerfile: php-fpm.dockerfile
    working_dir: /application
    volumes:
      - ./:/application
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/application
    ports:
      - "8000:8000"
    depends_on:
      - php-fpm

  postgres:
    image: postgres:latest
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mutable
      - POSTGRES_USER=mutable
      - POSTGRES_PASSWORD=mutable
    ports:
      - "5432:5432"

volumes:
  dbdata: